In [2]:
import pandas as pd
import numpy as np

location = "downloads/datasets/DC_Properties.csv"
df = pd.read_csv(location)

df.head()

C:\Users\D\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW

In [3]:
writer = pd.ExcelWriter('dcprop_datafram.xlsx', engine = 'xlsxwriter')
df.to_excel(writer, sheet_name='Initial DC Prop file')
writer.save()

In [4]:
df.columns

Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

In [6]:
df['ROOMS'].max()

48

In [7]:
df['ROOMS'].min()

0

In [8]:
df.describe()

,Unnamed: 0,BATHRM,HF_BATHRM,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,EYB,STORIES,...,USECODE,LANDAREA,CMPLX_NUM,LIVING_GBA,ZIPCODE,LATITUDE,LONGITUDE,CENSUS_TRACT,X,Y
count,158957.000000,158957.000000,158957.000000,106696.000000,158957.000000,158957.000000,158686.000000,80928.000000,158957.000000,106652.000000,...,158957.000000,158957.000000,52261.000000,52261.000000,158956.000000,158956.000000,158956.000000,158956.000000,158720.000000,158720.000000
mean,79478.000000,1.810678,0.458237,1.198039,6.187736,2.732506,1941.987579,1998.243537,1963.718024,2.091793,...,14.252999,2473.282158,2371.544249,888.834542,20012.694563,38.914854,-77.016676,5348.216324,-77.016712,38.914846
std,45887.077707,0.976396,0.587571,0.596924,2.618165,1.358864,33.640234,16.575786,24.923150,2.933323,...,3.725736,5059.046023,1114.272364,420.185822,15.627084,0.031723,0.040938,3369.645953,0.040933,0.031682
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1754.000000,20.000000,1800.000000,0.000000,...,11.000000,0.000000,1001.000000,0.000000,20001.000000,38.819731,-77.113909,100.000000,-77.113135,38.820576
25%,39739.000000,1.000000,0.000000,1.000000,4.000000,2.000000,1918.000000,1985.000000,1954.000000,2.000000,...,11.000000,697.000000,1501.000000,616.000000,20007.000000,38.895425,-77.042892,2102.000000,-77.042894,38.895432
50%,79478.000000,2.000000,0.000000,1.000000,6.000000,3.000000,1937.000000,2004.000000,1963.000000,2.000000,...,13.000000,1649.000000,2265.000000,783.000000,20011.000000,38.915337,-77.019596,5201.000000,-77.019581,38.915229
75%,119217.000000,2.000000,1.000000,1.000000,7.000000,3.000000,1960.000000,2010.000000,1975.000000,2.000000,...,17.000000,3000.000000,2910.000000,1060.000000,20018.000000,38.936075,-76.988626,8302.000000,-76.988842,38.936077
max,158956.000000,14.000000,11.000000,6.000000,48.000000,24.000000,2019.000000,2019.000000,2018.000000,826.000000,...,117.000000,942632.000000,5621.000000,8553.000000,20392.000000,38.995540,-76.909758,11100.000000,-76.910511,38.993646

In [14]:
df.groupby(['ZIPCODE','PRICE','BEDRM']).mean()

                         Unnamed: 0  BATHRM  HF_BATHRM  NUM_UNITS  ROOMS  \
ZIPCODE PRICE     BEDRM
20001.0 1.0       1        148694.0     1.0        0.0        NaN    3.0
        250.0     2         49443.0     2.0        0.0        2.0    8.0
                  5         55048.0     3.0        0.0        1.0    9.0
                  6         54909.0     5.0        2.0        2.0   10.0
        500.0     2         49470.0     2.0        0.0        2.0    6.0
                  4         57413.0     3.0        0.5        2.0    8.0
                  7          5516.0     2.0        1.0        2.0   15.0
        936.0     4          3330.0     2.0        1.0        1.0    9.0
        5000.0    3         54953.0     2.0        1.0        2.0    6.0
        5643.0    1        157136.0     1.0        1.0        NaN    3.0
        6000.0    1        134589.0     1.0        0.0        NaN    3.0
        8500.0    1        133745.0     1.0        0.0        NaN    3.0
        9000.0    1        134587.0     1.0        0.0        NaN    3.0
                  3         59895.0     1.0        0.0        1.0    7.0
        10000.0   1        141627.0     1.0        0.0        NaN    3.0
        12000.0   1        133751.0     1.0        0.0        NaN    3.0
        13350.0   2        145733.0     1.0        0.0        NaN    4.0
        16000.0   1        133759.0     1.0        0.0        NaN    3.0
        17000.0   2        147106.0     2.0        0.0        NaN    4.0
        19900.0   1        149267.0     1.0        0.0        NaN    3.0
        20000.0   1        149240.0     1.0        0.0        NaN    3.0
                  2        156330.0     2.0        0.0        NaN    4.0
                  4         52585.0     3.0        1.0        1.0    8.0
        21027.0   3         54276.0     1.0        0.0        1.0    6.0
        23900.0   4          4507.0     3.0        0.0        3.0   10.0
        25000.0   1        134576.0     1.0        0.0        NaN    3.0
                  3          4376.0     1.0        0.0        1.0    6.0
                  4         53142.0     2.0        0.0        1.0    6.0
                  6          1567.0     3.0        0.0        2.0   11.0
        26000.0   1        134166.5     1.0        0.0        NaN    3.0
...                             ...     ...        ...        ...    ...
20392.0 435000.0  2        112181.0     1.0        1.0        NaN    4.0
        439000.0  2        108435.0     1.0        0.0        NaN    4.0
        440000.0  2        112402.0     2.0        0.0        NaN    5.0
        445000.0  2        111327.0     1.0        0.0        NaN    4.0
        449000.0  1        112147.0     1.0        1.0        NaN    4.0
        460000.0  2        112148.0     2.0        0.0        NaN    5.0
        467000.0  1        112161.0     1.0        0.0        NaN    5.0
        470000.0  2        112160.0     2.0        0.0        NaN    5.0
        485000.0  2        108427.0     2.0        0.0        NaN    5.0
        490000.0  2        110077.5     2.0        0.0        NaN    5.0
        492182.0  2        111314.0     2.0        0.0        NaN    5.0
        495000.0  2        110307.5     2.0        0.0        NaN    5.0
        503012.0  2        108444.0     2.0        0.0        NaN    5.0
        525000.0  2        108474.0     2.0        0.0        NaN    5.0
        530000.0  2        109892.0     2.0        0.0        NaN    5.0
        550000.0  2        112410.0     2.0        0.0        NaN    5.0
        552000.0  2        111289.0     2.0        0.0        NaN    5.0
        555000.0  2        111298.0     2.0        0.0        NaN    5.0
        563000.0  2        108423.0     2.0        0.0        NaN    5.0
        570000.0  2        108472.0     2.0        0.0        NaN    5.0
        595000.0  2        108468.0     2.0        0.0        NaN    5.0
        599000.0  2        108470.0     2.0        0.0        NaN    5.0
        610000.0  2        111316.0     2.0        0.0        NaN    5.0
        612500.0  2        112176.0     2.0        1.0        NaN    6.0
        615000.0  2        108425.0     2.0        0.0        NaN    5.0
        650000.0  2        111320.0     2.0        0.0        NaN    5.0
        655000.0  2        112171.0     2.0        1.0        NaN    6.0
        709070.0  2        112169.0     2.0        1.0        NaN    6.0
        799000.0  3        112174.0     3.0        0.0        NaN    6.0
        1020000.0 3        112173.0     3.0        0.0        NaN    6.0

                            AYB  YR_RMDL     EYB  STORIES  SALE_NUM  \
ZIPCODE PRICE     BEDRM
20001.0 1.0       1      2007.0      NaN  2007.0      NaN       3.0
        250.0     2      1902.0      NaN  1964.0      2.0       1.0
                  5      1909.0   2003.0  1963.0      2.0       1.0
                  6      1906.0   2012.0  1975.0      3.0       1.0
        500.0     2         NaN      NaN  1954.0      2.0       1.0
                  4      1904.5   2001.0  1964.5      2.5       1.0
                  7      1916.0      NaN  1957.0      3.0       1.0
        936.0     4      1900.0   1996.0  1969.0      2.0       2.0
        5000.0    3      1913.0   1986.0  1967.0      2.0       1.0
        5643.0    1      2008.0      NaN  2008.0      NaN       4.0
        6000.0    1      1945.0   1985.0  1945.0      NaN       1.0
        8500.0    1      1945.0   1985.0  1945.0      NaN       1.0
        9000.0    1      1945.0   1985.0  1945.0      NaN       1.0
                  3      1909.0      NaN  1950.0      2.0       1.0
        10000.0   1      1975.5   1995.5  1975.5      NaN       1.0
        12000.0   1      1945.0   1985.0  1945.0      NaN       1.0
        13350.0   2      1937.0   2011.0  1937.0      NaN       3.0
        16000.0   1      1945.0   1985.0  1945.0      NaN       1.0
        17000.0   2      2006.0   2006.0  2006.0      NaN       3.0
        19900.0   1      1925.0   1984.0  1925.0      NaN       1.0
        20000.0   1      1925.0   1984.0  1925.0      NaN       1.0
                  2      2007.0      NaN  2007.0      NaN       1.0
                  4      1914.0   2005.0  1967.0      2.0       1.0
        21027.0   3      1906.0      NaN  1954.0      2.0       1.0
        23900.0   4      2002.0   2004.0  2007.0      3.0       1.0
        25000.0   1      1945.0   1985.0  1945.0      NaN       1.0
                  3      1890.0      NaN  1954.0      2.0       1.0
                  4      1907.0      NaN  1954.0      3.0       1.0
                  6      1880.0      NaN  1957.0      2.0       1.0
        26000.0   1      1945.0   1985.0  1945.0      NaN       1.0
...                         ...      ...     ...      ...       ...
20392.0 435000.0  2      1941.0      NaN  1941.0      NaN       1.0
        439000.0  2      1988.0      NaN  1988.0      NaN       6.0
        440000.0  2      1941.0      NaN  1941.0      NaN       2.0
        445000.0  2      1988.0      NaN  1988.0      NaN       1.0
        449000.0  1      1988.0      NaN  1988.0      NaN       4.0
        460000.0  2      1988.0      NaN  1988.0      NaN       1.0
        467000.0  1      1988.0      NaN  1988.0      NaN       1.0
        470000.0  2      1988.0      NaN  1988.0      NaN       4.0
        485000.0  2      1988.0      NaN  1988.0      NaN       3.0
        490000.0  2      1964.5      NaN  1964.5      NaN       2.0
        492182.0  2      1988.0      NaN  1988.0      NaN       6.0
        495000.0  2      1988.0      NaN  1988.0      NaN       1.0
        503012.0  2      1988.0      NaN  1988.0      NaN       3.0
        525000.0  2      1988.0      NaN  1988.0      NaN       1.0
        530000.0  2      1988.0      NaN  1988.0      NaN       2.5
        550000.0  2      1941.0      NaN  1941.0      NaN       1.0
        552000.0  2      1988.0      NaN  1988.0      NaN       1.0
        555000.0  2      1988.0      NaN  1988.0      NaN       3.5
        563000.0  2      1988.0      NaN  1988.0      NaN       3.0
        570000.0  2      1988.0      NaN  1988.0      NaN       1.0
        595000.0  2      1988.0      NaN  1988.0      NaN       1.0
        599000.0  2      1988.0      NaN  1988.0      NaN       3.0
        610000.0  2      1988.0      NaN  1988.0      NaN       1.0
        612500.0  2      1988.0      NaN  1988.0      NaN       2.0
        615000.0  2      1988.0      NaN  1988.0      NaN       3.0
        650000.0  2      1988.0      NaN  1988.0      NaN       1.0
        655000.0  2      1988.0      NaN  1988.0      NaN       4.0
        709070.0  2      1988.0      NaN  1988.0      NaN       1.0
        799000.0  3      1988.0      NaN  1988.0      NaN       1.0
        1020000.0 3      1988.0      NaN  1988.0      NaN       1.0

                           ...      FIREPLACES  USECODE  LANDAREA  CMPLX_NUM  \
ZIPCODE PRICE     BEDRM    ...
20001.0 1.0       1        ...             0.0     17.0      93.0     2871.0
        250.0     2        ...             0.0     23.0    1535.0        NaN
                  5        ...             1.0     11.0    1152.0        NaN
                  6        ...             0.0     24.0    2520.0        NaN
        500.0     2        ...             0.0     11.0    1587.0        NaN
                  4        ...             0.0     24.0    1485.0        NaN
                  7        ...             0.0     24.0    2031.0        NaN
        936.0     4        ...             3.0     11.0    1398.0        NaN
        5000.0    3        ...             0.0     24.0    2391.0        NaN
        5643.0    1        ...             0.0     17.0      11.0     2898.0
        6000.0    1        ...             0.0     17.0     217.0     2260.0
        8500.0    1        ...             0.0     17.0     221.0     2260.0
        9000.0    1        ...             0.0     17.0     252.0     2260.0
                  3        ...             0.0     11.0    2058.0        NaN
        10000.0   1        ...             0.0     17.0     174.5     2532.5
        12000.0   1        ...             0.0     17.0     226.0     2260.0
        13350.0   2        ...             0.0     16.0     180.0     1416.0
        16000.0   1        ...             0.0     17.0     211.0     2260.0
        17000.0   2        ...             0.0     17.0     165.0     2819.0
        19900.0   1        ...             0.0     16.0     474.0     2284.0
        20000.0   1        ...             0.0     16.0     474.0     2284.0
                  2        ...             0.0     17.0     167.0     2875.0
                  4        ...             0.0     11.0    2356.0        NaN
        21027.0   3        ...             0.0     11.0    1452.0        NaN
        23900.0   4        ...             0.0     23.0     869.0        NaN
        25000.0   1        ...             0.0     17.0     211.0     2260.0
                  3        ...             0.0     11.0    1046.0        NaN
                  4        ...             0.0     11.0     780.0        NaN
                  6        ...             0.0     24.0    1867.0        NaN
        26000.0   1        ...             0.0     17.0     253.5     2260.0
...                        ...             ...      ...       ...        ...
20392.0 435000.0  2        ...             1.0     17.0     387.0     1060.0
        439000.0  2        ...             0.0     17.0     260.0     1059.0
        440000.0  2        ...             1.0     17.0     516.0     1060.0
        445000.0  2        ...             0.0     17.0     256.0     1059.0
        449000.0  1        ...             0.0     17.0     256.0     1059.0
        460000.0  2        ...             0.0     17.0     307.0     1059.0
        467000.0  1        ...             0.0     17.0     277.0     1059.0
        470000.0  2        ...             0.0     17.0     339.0     1059.0
        485000.0  2        ...             0.0     17.0     308.0     1059.0
        490000.0  2        ...             0.0     17.0     430.5     1059.5
        492182.0  2        ...             0.0     17.0     320.0     1059.0
        495000.0  2        ...             0.0     17.0     318.5     1059.0
        503012.0  2        ...             0.0     17.0     345.0     1059.0
        525000.0  2        ...             0.0     17.0     308.0     1059.0
        530000.0  2        ...             0.0     17.0     332.0     1059.0
        550000.0  2        ...             1.0     17.0     516.0     1060.0
        552000.0  2        ...             0.0     17.0     320.0     1059.0
        555000.0  2        ...             0.5     17.0     326.0     1059.0
        563000.0  2        ...             0.0     17.0     408.0     1059.0
        570000.0  2        ...             0.0     17.0     364.0     1059.0
        595000.0  2        ...             0.0     17.0     345.0     1059.0
        599000.0  2        ...             0.0     17.0     408.0     1059.0
        610000.0  2        ...             0.0     17.0     319.0     1059.0
        612500.0  2        ...             1.0     17.0     455.0     1059.0
        615000.0  2        ...             0.0     17.0     364.0     1059.0
        650000.0  2        ...             0.0     17.0     408.0     1059.0
        655000.0  2        ...             1.0     17.0     579.0     1059.0
        709070.0  2        ...             1.0     17.0     520.0     1059.0
        799000.0  3        ...             1.0     17.0     658.0     1059.0
        1020000.0 3        ...             1.0     17.0     662.0     1059.0

                         LIVING_GBA   LATITUDE  LONGITUDE  CENSUS_TRACT  \
ZIPCODE PRICE     BEDRM
20001.0 1.0       1           670.0  38.900439 -77.015750        4702.0
        250.0     2             NaN  38.928248 -77.025875        3100.0
                  5             NaN  38.916807 -77.011975        3301.0
                  6             NaN  38.921546 -77.010958        3301.0
        500.0     2             NaN  38.926493 -77.025620        3500.0
                  4             NaN  38.916448 -77.014201        3350.5
                  7             NaN  38.906504 -77.010773        4701.0
        936.0     4             NaN  38.909843 -77.020603        4801.0
        5000.0    3             NaN  38.919385 -77.010909        3301.0
        5643.0    1           877.0  38.903141 -77.017776        4701.0
        6000.0    1           483.0  38.908030 -77.024777        4902.0
        8500.0    1           523.0  38.908030 -77.024777        4902.0
        9000.0    1           559.0  38.908030 -77.024777        4902.0
                  3             NaN  38.920817 -77.013313        3301.0
        10000.0   1           609.0  38.906395 -77.024537        4902.0
        12000.0   1           521.0  38.908030 -77.024777        4902.0
        13350.0   2           735.0  38.915373 -77.013885        3301.0
        16000.0   1           491.0  38.908030 -77.024777        4902.0
        17000.0   2          1388.0  38.900439 -77.015750        4702.0
        19900.0   1           590.0  38.906499 -77.010700        4701.0
        20000.0   1           503.0  38.906499 -77.010700        4701.0
                  2          1039.0  38.903141 -77.017776        4701.0
                  4             NaN  38.916611 -77.014689        3400.0
        21027.0   3             NaN  38.917262 -77.016788        3400.0
        23900.0   4             NaN  38.919018 -77.026579        4400.0
        25000.0   1           491.0  38.908030 -77.024777        4902.0
                  3             NaN  38.918277 -77.026227        4400.0
                  4             NaN  38.917170 -77.018230        3400.0
                  6             NaN  38.912057 -77.019170        4801.0
        26000.0   1           579.0  38.908030 -77.024777        4902.0
...                             ...        ...        ...           ...
20392.0 435000.0  2           876.0  38.920661 -77.067293         400.0
        439000.0  2           832.0  38.920661 -77.067293         400.0
        440000.0  2          1171.0  38.920661 -77.067293         400.0
        445000.0  2           817.0  38.920661 -77.067293         400.0
        449000.0  1           817.0  38.920661 -77.067293         400.0
        460000.0  2           980.0  38.920661 -77.067293         400.0
        467000.0  1           885.0  38.920661 -77.067293         400.0
        470000.0  2          1084.0  38.920661 -77.067293         400.0
        485000.0  2           986.0  38.920661 -77.067293         400.0
        490000.0  2          1137.0  38.920661 -77.067293         400.0
        492182.0  2          1023.0  38.920661 -77.067293         400.0
        495000.0  2          1017.5  38.920661 -77.067293         400.0
        503012.0  2          1103.0  38.920661 -77.067293         400.0
        525000.0  2           986.0  38.920661 -77.067293         400.0
        530000.0  2          1061.5  38.920661 -77.067293         400.0
        550000.0  2          1171.0  38.920661 -77.067293         400.0
        552000.0  2          1023.0  38.920661 -77.067293         400.0
        555000.0  2          1041.5  38.920661 -77.067293         400.0
        563000.0  2          1304.0  38.920661 -77.067293         400.0
        570000.0  2          1165.0  38.920661 -77.067293         400.0
        595000.0  2          1103.0  38.920661 -77.067293         400.0
        599000.0  2          1304.0  38.920661 -77.067293         400.0
        610000.0  2          1020.0  38.920661 -77.067293         400.0
        612500.0  2          1454.0  38.920661 -77.067293         400.0
        615000.0  2          1165.0  38.920661 -77.067293         400.0
        650000.0  2          1304.0  38.920661 -77.067293         400.0
        655000.0  2          1851.0  38.920661 -77.067293         400.0
        709070.0  2          1663.0  38.920661 -77.067293         400.0
        799000.0  3          2103.0  38.920661 -77.067293         400.0
        1020000.0 3          2117.0  38.920661 -77.067293         400.0

                                 X          Y
ZIPCODE PRICE     BEDRM
20001.0 1.0       1     -77.015752  38.900447
        250.0     2     -77.025553  38.928425
                  5     -77.010980  38.916722
                  6     -77.010605  38.921832
        500.0     2     -77.024503  38.926761
                  4     -77.013881  38.916520
                  7     -77.010702  38.906507
        936.0     4     -77.020725  38.910531
        5000.0    3     -77.010659  38.919682
        5643.0    1     -77.017778  38.903148
        6000.0    1     -77.024779  38.908038
        8500.0    1     -77.024779  38.908038
        9000.0    1     -77.024779  38.908038
                  3     -77.013316  38.920608
        10000.0   1     -77.024540  38.906403
        12000.0   1     -77.024779  38.908038
        13350.0   2     -77.013887  38.915381
        16000.0   1     -77.024779  38.908038
        17000.0   2     -77.015752  38.900447
        19900.0   1     -77.010702  38.906507
        20000.0   1     -77.010702  38.906507
                  2     -77.017778  38.903148
                  4     -77.014736  38.916568
        21027.0   3     -77.016731  38.917174
        23900.0   4     -77.026365  38.918751
        25000.0   1     -77.024779  38.908038
                  3     -77.026365  38.918751
                  4     -77.018101  38.917165
                  6     -77.019422  38.911848
        26000.0   1     -77.024779  38.908038
...                            ...        ...
20392.0 435000.0  2     -77.067295  38.920669
        439000.0  2     -77.067295  38.920669
        440000.0  2     -77.067295  38.920669
        445000.0  2     -77.067295  38.920669
        449000.0  1     -77.067295  38.920669
        460000.0  2     -77.067295  38.920669
        467000.0  1     -77.067295  38.920669
        470000.0  2     -77.067295  38.920669

In [15]:
pd.pivot_table(df, index=['ZIPCODE'])

,AYB,BATHRM,BEDRM,BLDG_NUM,CENSUS_TRACT,CMPLX_NUM,EYB,FIREPLACES,GBA,HF_BATHRM,...,NUM_UNITS,PRICE,ROOMS,SALE_NUM,STORIES,USECODE,Unnamed: 0,X,Y,YR_RMDL
ZIPCODE,,,,,,,,,,,,,,,,,,,,,
20001.0,1944.296908,1.752109,2.515594,1.000569,4426.667457,3075.659109,1972.332828,0.233956,1684.339766,0.342213,...,1.361848,5.215550e+05,5.464025,1.835245,2.185235,15.745758,87688.040478,-77.018922,38.911859,2003.997460
20002.0,1924.439656,1.807051,2.898774,1.000307,8574.291723,3202.751887,1959.808584,0.648620,1536.289829,0.432863,...,1.376838,4.628894e+05,6.561619,1.818945,2.125015,14.362845,59142.942121,-76.991251,38.901550,2001.201243
20003.0,1927.502625,1.877355,2.767187,1.000624,6845.625702,3056.194976,1967.295945,0.642795,1616.755636,0.504554,...,1.312470,5.992484e+05,6.424454,1.755958,2.195206,14.649158,37851.539488,-76.991109,38.884212,1996.634495
20004.0,1999.966728,1.260628,1.208872,1.000000,5800.000000,3065.667283,1999.882625,0.002773,NaN,0.193161,...,NaN,4.755701e+05,3.432532,1.923290,NaN,17.091497,156753.257856,-77.022506,38.895391,2003.000000
20005.0,1959.517920,1.433608,1.375147,1.000000,5681.060223,2648.242929,1962.656874,86.711810,2483.193694,0.142186,...,2.103604,2.813137e+06,3.765864,1.976792,2.632353,17.022327,122849.154524,-77.031086,38.907635,1995.012685
20006.0,1959.491525,1.025424,0.220339,1.000000,10800.000000,2025.000000,1960.000000,0.016949,2651.000000,0.008475,...,1.000000,1.959069e+05,2.254237,1.584746,3.000000,16.949153,115493.025424,-77.045532,38.896937,1981.161017
20007.0,1936.747423,2.229815,2.901429,1.001661,384.865766,2410.201071,1969.578580,0.974970,2162.538128,0.559420,...,1.129555,9.794061e+05,6.637391,1.726437,2.358887,13.647359,52782.536383,-77.072765,38.914425,1993.973843
20008.0,1940.429981,2.264961,2.824291,1.001323,1399.151889,1563.928487,1960.220703,0.904132,3006.724361,0.531392,...,1.074346,8.522766e+05,6.567417,1.566240,2.323068,14.671666,92137.783561,-77.059899,38.935939,1992.732423
20009.0,1932.782506,1.677625,2.101359,1.000152,4126.949283,2156.422629,1949.440285,0.521525,2205.807692,0.274998,...,1.625506,6.215259e+05,4.997343,1.805558,2.589141,16.603295,104716.020879,-77.037655,38.918884,1994.690317
20010.0,1922.907676,1.877411,3.019757,1.000000,2900.932638,2570.695490,1956.257623,0.353298,1775.503624,0.379434,...,1.297872,5.070154e+05,6.278002,1.696951,2.267360,14.701929,77567.046360,-77.031411,38.932724,2004.755108
20011.0,1933.187243,1.763760,3.216365,1.000183,3541.576994,3125.653263,1957.592894,0.390105,1562.791372,0.553510,...,1.118234,4.259763e+05,7.030210,1.628914,2.008229,12.735201,64510.243456,-77.019769,38.952592,2004.312754
20012.0,1941.522120,2.050753,3.359883,1.000729,3472.674356,3089.335312,1963.291161,0.937834,1851.464163,0.689169,...,1.017985,4.755227e+05,7.251821,1.490044,1.904472,12.519184,59569.162943,-77.027150,38.977338,2006.001742
20015.0,1941.053983,2.356193,3.450628,1.000375,1352.114484,3105.044693,1967.881769,1.144088,2155.493542,0.810568,...,1.010208,7.703746e+05,7.623009,1.519393,2.061575,12.531385,44506.818250,-77.068057,38.966119,1998.798758
20016.0,1950.880294,2.205656,2.903138,1.000470,908.404547,1783.194597,1969.201898,1.070462,2376.575986,0.629838,...,1.026482,5.914537e+06,6.649474,1.630308,2.082686,13.829951,64325.985156,-77.086082,38.938829,1993.884534
20017.0,1949.104886,1.677873,3.021700,1.000178,9158.954109,3283.165689,1965.311455,0.360370,1445.019433,0.586268,...,1.097571,4.087405e+05,6.597118,1.551583,2.028893,12.961757,77827.041089,-76.992191,38.939175,2000.027795
20018.0,1948.102915,1.756790,3.103704,1.000176,9688.544974,3030.484157,1968.902469,0.532804,1517.281909,0.609347,...,1.060029,3.691101e+05,6.544092,1.648677,1.919432,12.640917,85063.644268,-76.972549,38.928623,2000.732202
20019.0,1953.548322,1.571279,2.823728,1.000080,8623.784074,2202.093023,1965.900787,0.116792,1253.001039,0.362097,...,1.148680,2.302621e+05,6.347488,1.577139,1.884913,13.066704,91952.942206,-76.937593,38.890768,2003.248227
20020.0,1952.454471,1.575931,2.823355,1.003570,7901.850790,1702.724611,1965.815094,0.261091,1433.272608,0.445181,...,1.176139,2.281464e+05,6.357369,1.519531,1.969857,13.406935,103193.366140,-76.969750,38.862377,1995.613565
20024.0,1970.807283,1.441868,1.550725,1.000000,10194.460548,2713.810058,1973.510145,0.089533,1515.082692,0.244444,...,1.250000,3.808846e+05,4.202899,1.658293,2.135577,16.253784,126311.950081,-77.016755,38.877955,2007.554124
20032.0,1958.017035,1.662884,2.862845,1.000391,9649.692232,1723.671004,1967.492467,0.086089,1427.391326,0.463901,...,1.286741,3.235769e+05,6.512620,1.566230,2.035874,14.006065,105621.327333,-76.998665,38.835870,2002.546774
20036.0,1947.680761,1.284355,1.044926,1.000000,6174.610994,1783.965773,1952.262685,0.288055,2650.294964,0.084038,...,1.956835,4.015452e+05,3.471987,1.699789,2.886691,17.112579,111388.080867,-77.041530,38.909112,1982.907589
20037.0,1969.182842,1.422788,1.319035,1.000000,6023.109920,1642.310914,1969.031635,0.511796,1544.352941,0.222788,...,1.441176,6.124601e+05,3.790885,1.731367,2.279412,16.810188,105902.845040,-77.050750,38.904124,1987.553310
20052.0,1892.210526,1.894737,3.947368,1.000000,10800.000000,NaN,1963.789474,0.157895,1979.684211,0.368421,...,1.263158,5.378571e+05,7.894737,1.000000,2.631579,11.894737,3027.578947,-77.047817,38.897717,2005.000000
20392.0,1981.935484,1.295699,1.241935,1.000000,400.000000,1059.129032,1981.935484,0.161290,NaN,0.177419,...,NaN,3.489169e+05,4.145161,1.752688,NaN,17.000000,110556.161290,-77.067295,38.920669,NaN

In [16]:
pd.pivot_table(df, values=['PRICE'], index =['ZIPCODE'])

                PRICE
ZIPCODE
20001.0  5.215550e+05
20002.0  4.628894e+05
20003.0  5.992484e+05
20004.0  4.755701e+05
20005.0  2.813137e+06
20006.0  1.959069e+05
20007.0  9.794061e+05
20008.0  8.522766e+05
20009.0  6.215259e+05
20010.0  5.070154e+05
20011.0  4.259763e+05
20012.0  4.755227e+05
20015.0  7.703746e+05
20016.0  5.914537e+06
20017.0  4.087405e+05
20018.0  3.691101e+05
20019.0  2.302621e+05
20020.0  2.281464e+05
20024.0  3.808846e+05
20032.0  3.235769e+05
20036.0  4.015452e+05
20037.0  6.124601e+05
20052.0  5.378571e+05
20392.0  3.489169e+05

In [18]:
df.isnull().sum()

Unnamed: 0                 0
BATHRM                     0
HF_BATHRM                  0
HEAT                       0
AC                         0
NUM_UNITS              52261
ROOMS                      0
BEDRM                      0
AYB                      271
YR_RMDL                78029
EYB                        0
STORIES                52305
SALEDATE               26770
PRICE                  60741
QUALIFIED                  0
SALE_NUM                   0
GBA                    52261
BLDG_NUM                   0
STYLE                  52261
STRUCT                 52261
GRADE                  52261
CNDTN                  52261
EXTWALL                52261
ROOF                   52261
INTWALL                52261
KITCHENS               52262
FIREPLACES                 0
USECODE                    0
LANDAREA                   0
GIS_LAST_MOD_DTTM          0
SOURCE                     0
CMPLX_NUM             106696
LIVING_GBA            106696
FULLADDRESS            52917
CITY                   52906
STATE                  52906
ZIPCODE                    1
NATIONALGRID           52906
LATITUDE                   1
LONGITUDE                  1
ASSESSMENT_NBHD            1
ASSESSMENT_SUBNBHD     32551
CENSUS_TRACT               1
CENSUS_BLOCK           52906
WARD                       1
SQUARE                     0
X                        237
Y                        237
QUADRANT                 237
dtype: int64

In [20]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...
158927    False
158928    False
158929    False
158930    False
158931    False
158932    False
158933    False
158934    False
158935    False
158936    False
158937    False
158938    False
158939    False
158940    False
158941    False
158942    False
158943    False
158944    False
158945    False
158946    False
158947    False
158948    False
158949    False
158950    False
158951    False
158952    False
158953    False
158954    False
158955    False
158956    False
Length: 158957, dtype: bool

In [22]:
df.loc[df.duplicated()]

Empty DataFrame
Columns: [Unnamed: 0, BATHRM, HF_BATHRM, HEAT, AC, NUM_UNITS, ROOMS, BEDRM, AYB, YR_RMDL, EYB, STORIES, SALEDATE, PRICE, QUALIFIED, SALE_NUM, GBA, BLDG_NUM, STYLE, STRUCT, GRADE, CNDTN, EXTWALL, ROOF, INTWALL, KITCHENS, FIREPLACES, USECODE, LANDAREA, GIS_LAST_MOD_DTTM, SOURCE, CMPLX_NUM, LIVING_GBA, FULLADDRESS, CITY, STATE, ZIPCODE, NATIONALGRID, LATITUDE, LONGITUDE, ASSESSMENT_NBHD, ASSESSMENT_SUBNBHD, CENSUS_TRACT, CENSUS_BLOCK, WARD, SQUARE, X, Y, QUADRANT]
Index: []

[0 rows x 49 columns]